cloud:
  aws:
    region:
      static: ap-south-1
      auto: false
    credentials:
      access-key: give your access key here
      secret-key: give your secret key here
    end-point:
      uri: give here  your sqs end point uri here -example https://sqs.ap-south-1.amazonaws.com/123456789012/my-queue